language: ruby

cache:
  directories:
  - $HOME/protobuf

sudo: false

before_install:
  - bash install-protobuf.sh

# check what has been installed by listing contents of protobuf folder
before_script:
  - ls -R $HOME/protobuf

# let's use protobuf
script:
  - $HOME/protobuf/bin/protoc --java_out=./  ./core/*.proto ./api/*.proto
  - ls -l